// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJ9vjiCbkBecTSStUPzYK51HVdW70UkE',
    appId: '1:928622878632:web:5072ad8a0fc734918ec79d',
    messagingSenderId: '928622878632',
    projectId: 'browsestations',
    authDomain: 'browsestations.firebaseapp.com',
    storageBucket: 'browsestations.firebasestorage.app',
    measurementId: 'G-J0WL6L7V0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfRwizP0e0b3iWoA27IGs6LONnkwDxOQ',
    appId: '1:928622878632:android:ad92a75c6b26f85e8ec79d',
    messagingSenderId: '928622878632',
    projectId: 'browsestations',
    storageBucket: 'browsestations.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxZdAkCm08_JemP_kon3w9gxMDyP3Xkk',
    appId: '1:928622878632:ios:44cae1f5299a84258ec79d',
    messagingSenderId: '928622878632',
    projectId: 'browsestations',
    storageBucket: 'browsestations.firebasestorage.app',
    iosBundleId: 'com.example.browseStation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUxZdAkCm08_JemP_kon3w9gxMDyP3Xkk',
    appId: '1:928622878632:ios:44cae1f5299a84258ec79d',
    messagingSenderId: '928622878632',
    projectId: 'browsestations',
    storageBucket: 'browsestations.firebasestorage.app',
    iosBundleId: 'com.example.browseStation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdJ9vjiCbkBecTSStUPzYK51HVdW70UkE',
    appId: '1:928622878632:web:a3f8cdd6f90aacdc8ec79d',
    messagingSenderId: '928622878632',
    projectId: 'browsestations',
    authDomain: 'browsestations.firebaseapp.com',
    storageBucket: 'browsestations.firebasestorage.app',
    measurementId: 'G-FP73KG1CW7',
  );
}
